# Generated by Django 6.0.3 on 2026-04-25 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_comment_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='published_date',
            field=models.DateTimeField(auto_created=True, blank=True, null=True, verbose_name='Дата публікаціїї'),
        ),
    ]
